### ISSUE TITLE
frida hooking works fine from CLI , But not working from Python code

### ISSUE THREAD

**Issue by rupesh131077** [oleavr/frida-agent-example#11]
Hi.
This is regarding Frida Hook issue
 I am working on Linux Ubuntu 18.04 PC and I am able to hooks Frida JS script from  CLI,, But If I Try from Python, I am not able to hook the code,, can you please help on the same

sample code I have taken from https://book.hacktricks.xyz/mobile-apps-pentesting/android-app-pentesting/frida-tutorial.
please help me

**Comment by oleavr** [comment]
Please try with the latest version of Frida.
