### ISSUE TITLE
update example run js error

### ISSUE THREAD

**Issue by c0618** [oleavr/frida-agent-example#12]
Hi : oleavr 
     I updated the latest example and the following error occurred

`Failed to load script: script(line 4): SyntaxError: parse error `

your code is :
`var tcp_network_func = Process.getModuleByName('libSystem.B.dylib').enumerateExports().filter((ex => ex.type === 'function' && ['connect', 'recv', 'send', 'read', 'write'].some(prefix => ex.name.indexOf(prefix) === 0)));
tcp_network_func.forEach(ex => {
    console.log(JSON.stringify(ex));
});
`

**Comment by c0618** [comment]
After testing, it may be an error caused by updating "frida-compile": "^10.0.0"

**Comment by oleavr** [comment]
@c0618 This example now requires Frida >= 14.0.0, released yesterday. (frida-compile@10 no longer compiles the code to ES5, as our default runtime now supports ES2020.)
