### ISSUE TITLE
TS2300: Duplicate identifier 'WeakRef'

### ISSUE THREAD

**Issue by zhangbozhb** [oleavr/frida-agent-example#13]
I clone this repo. my node version v15.3.0
It work well when i run command. 'npm install'
However if I run 'npm upgrade',and then run npm install, it report errors.

errors:
[TypeScript error:**/frida/node_modules/@types/frida-gum/index.d.ts(4803,19): Error TS2300: Duplicate identifier 'WeakRef'.] {
  fileName: **/frida/node_modules/@types/frida-gum/index.d.ts',
  line: 4803,
  column: 19,

**Comment by oleavr** [comment]
Fixed in 7f431454b2daba52e832844a73a40457f8442fe3.
