### ISSUE TITLE
libSystem.B.dylib error

### ISSUE THREAD

**Issue by aaeolus** [oleavr/frida-agent-example#17]
Error: unable to find module 'libSystem.B.dylib'
    at value (frida/runtime/core.js:281)
    at <anonymous> (agent/index.ts:10)
    at call (native)
    at o (node_modules/browser-pack/_prelude.js:1)
    at r (node_modules/browser-pack/_prelude.js:1)
    at <eval> (/_agent.js:33)

**Comment by oleavr** [comment]
This is an example agent, you will have to adjust it to match your operating system.

**Comment by milahu** [comment]
yepp, its confusing that the [first example](https://learnfrida.info/basic_usage/#writing-our-first-agent) of a frida agent
throws this error on non-macos platforms

`libSystem.B.dylib` on macos
`libc.so.6` on linux
...

this would more cross-platform

```js
// ReferenceError: 'process' is not defined
//log(`platform ${process.platform}`);

// print the first 16 functions of the system library
const libcNameList = [
  "libSystem.B.dylib", // macos
  "libc.so.6", // linux
];
for (const libcName of libcNameList) {
    let module;
    try {
        module = Process.getModuleByName(libcName);
    } catch (e) {
        //log(String(e));
        continue;
    }
    log(`module ${libcName}:`);
    module
        .enumerateExports()
        .slice(0, 16)
        .forEach((exp, index) => {
            log(`export ${index}: ${exp.name}`);
        });
    break;
}
```
