### ISSUE TITLE
'enumerateExportsSync' does not exist on type 'typeof Module'

### ISSUE THREAD

**Issue by hac425xxx** [oleavr/frida-agent-example#19]
I tried to use enumerateExportsSync to traverse the symbols of the module, but I got an error, I can run it through python's create_script

![image](https://user-images.githubusercontent.com/56855299/156685748-69068000-5120-472e-bc06-51b2a40ad553.png)

**Comment by oleavr** [comment]
That API is deprecated and is intentionally not exposed by the TypeScript bindings. Use `enumerateExports()`, which now works the same way when not specifying any callbacks.
