### ISSUE TITLE
iphone4 ios 9.3.5 

### ISSUE THREAD

**Issue by gaplan** [oleavr/frida-agent-example#2]
frida -U -f re.frida.Gadget --no-pause -l _agent.js
     ____
    / _  |   Frida 12.0.3 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at http://www.frida.re/docs/home/
Spawned `re.frida.Gadget`. Resuming main thread!                        
Error: expected a pointer
    at repl1.js:94
    at o (repl1.js:1)
    at repl1.js:39
    at o (repl1.js:1)
    at r (repl1.js:1)
    at repl1.js:102
[iPhone 4S::re.frida.Gadget]->

**Comment by oleavr** [comment]
This project is just meant to serve as boilerplate, not meant to be used as-is. If you read the code you'll see why – it's assuming it's running on Android. (PR welcome though to use NSLog on iOS!)
