### ISSUE TITLE
_agent.js NOT like a normal js file

### ISSUE THREAD

**Issue by 0x79H** [oleavr/frida-agent-example#24]
Hi. I checkout the latest version (c709844d8dd47df8955172db104c76ceed81d6c6). When i run `npm run build` (`frida-compile agent/index.ts -o _agent.js -c`) , the output file `_agent.js` include emoji, and it not like a normal js file. I also try `npm run watch` (`frida-compile agent/index.ts -o _agent.js -w`)

I try to find the reason. I found [this](https://github.com/frida/frida-compile/blame/700bd39432416360b8650e3638bbd99798294e5d/src/compiler.ts#L539) at `frida-compile` , and understand the output is normal.

But i don't know why `_agnet.js` work in frida. Maybe it only work in Frida? Or new features of the js engine? Any helpful info?

I also try to find the parameters in `frida-compile` where I could get a normal javascript output file, but nothing there. What i miss?

Thanks.

**Comment by oleavr** [comment]
Hi,

The new frida-compile outputs a Frida-specific container format for multiple ESMs in a single .js, and that's what you're seeing.

Check out the new frida-tools -- there is now a frida-compile tool there and the REPL supports loading .ts files through `-l`.

Cheers!

**Comment by grubeli** [comment]
> Hi,
> 
> The new frida-compile outputs a Frida-specific container format for multiple ESMs in a single .js, and that's what you're seeing.
> 
> Check out the new frida-tools -- there is now a frida-compile tool there and the REPL supports loading .ts files through `-l`.
> 
> Cheers!

Can I use `.ts` files from a `.py` script similar to loading `.js` scripts?

**Comment by ChiChou** [comment]
> > Hi,
> > The new frida-compile outputs a Frida-specific container format for multiple ESMs in a single .js, and that's what you're seeing.
> > Check out the new frida-tools -- there is now a frida-compile tool there and the REPL supports loading .ts files through `-l`.
> > Cheers!
> 
> Can I use `.ts` files from a `.py` script similar to loading `.js` scripts?

I have the same issue here

**Comment by andreafioraldi** [comment]
> > > Hi,
> > > The new frida-compile outputs a Frida-specific container format for multiple ESMs in a single .js, and that's what you're seeing.
> > > Check out the new frida-tools -- there is now a frida-compile tool there and the REPL supports loading .ts files through `-l`.
> > > Cheers!
> > 
> > 
> > Can I use `.ts` files from a `.py` script similar to loading `.js` scripts?
> 
> I have the same issue here

+1

**Comment by ChiChou** [comment]
@andreafioraldi the problem is the line break on Windows. Mine solved by suppplying `newline='\n'` to `open`, then the rest remains the same

```py
with (filename).open('r', encoding='utf8', newline='\n') as fp:
        return fp.read()
```

**Comment by qiaozhi-4** [comment]
你好请问有解决吗

**Comment by muniategui** [comment]
> 你好请问有解决吗

Dude, you are writing just above the answer.
If you are in windows open('r', encoding='utf8', newline='\n') the utf8 and \n has to be set.
