### ISSUE TITLE
Documentation Error: Incorrect description of NativePointer.shl and NativePointer.shr methods.

### ISSUE THREAD

**Issue by moha-abdi** [oleavr/frida-agent-example#29]
Description:
The current documentation for the NativePointer.shl and NativePointer.shr methods contains errors in their method descriptions. The description for NativePointer.shl claims that the method performs a left shift operation (this << v), while it actually represents a right shift operation (this >> v). On the other hand, the description for NativePointer.shr claims to perform a right shift operation, but it is implemented as a left shift operation. These discrepancies could lead to confusion and incorrect usage of the methods. I hope you update this and thanks. 
**NOTE**:  both methods work as expected but what I meant is only the documentation.

Screenshots:
Shift Left: ![image](https://github.com/oleavr/frida-agent-example/assets/83307623/3311e1a2-4ea7-44a2-9fb5-ba2a73bab59e)

Shift Right: ![image](https://github.com/oleavr/frida-agent-example/assets/83307623/a58c4fb2-7fb5-4fe3-a263-542d60954980)

**Comment by oleavr** [comment]
Thanks for reporting! Could you please open a PR against our typings, at https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/frida-gum? Thanks! 🙌

**Comment by moha-abdi** [comment]
of course i will do that, and you are welcome.
