### ISSUE TITLE
Type 'null' is not assignable to type 'NativePointerValue'.

### ISSUE THREAD

**Issue by CCint3** [oleavr/frida-agent-example#3]
### Error:
i have the code in util.ts:
``` TypeScript
let gettid_ptr = Module.findExportByName(null, "gettid");

export const gettid = new NativeFunction(gettid_ptr, "uint32", []);
```

got the error:
```
TS2345: Argument of type 'NativePointer | null' is not assignable to parameter of type 

'NativePointerValue'.   Type 'null' is not assignable to type 'NativePointerValue'.
```

### Fix:
update the `frida-agent-example\node_modules\@types\frida-gum\index.d.ts` file of line 465:
``` TypeScript
static findExportByName(moduleName: string | null, exportName: string): NativePointer | null;
```
to
``` TypeScript
static findExportByName(moduleName: string | null, exportName: string): NativePointerValue;
```
Thanks.

@oleavr

**Comment by oleavr** [comment]
The TypeScript compiler is helpfully detecting that you're failing to check if `Module.findExportByName()` returns `null`. But you shouldn't do that unless you're writing code that needs to handle a certain export being missing, so use `Module.getExportByName()` instead.
