### ISSUE TITLE
Interceptor::flush is missing in the node.js package

### ISSUE THREAD

**Issue by Sh3idan** [oleavr/frida-agent-example#7]
In the frida-gum node-js package version 16.0.0, the function Interceptor::flush is missing. According to the documentation (https://frida.re/docs/javascript-api/#interceptor), we expect to have the following defintion in the index.d.ts file:

```typescript
    /**
     * Ensure any pending changes have been committed to memory.
     */
    function flush(): void;
```

I'm sorry if it is not the right place to report that.

**Comment by oleavr** [comment]
Ahh nice catch! Would you be interested in submitting a PR to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)? If it's too much hassle let me know and I can do it, but would be great if the change was attributed to you.

**Comment by Sh3idan** [comment]
I will look into doing this. Thanks for this link !
